import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.14.305/pdf.min.js"
          async
        ></script>
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
